#
# production configuration
#
spring:
  datasource:
    # RDS
    url: '{cipher}AQCSA0rRCM47HNSs74fdY2C0mznb/A8I6Bzd2F6wFdIDE33ViWmlO6XjZ5Ob/yYUxtqfXOMHgQWwUNf5jR1Mjm8vaEhqU32QbFXNzynFtWWrYg+s4a1j8NhWIGV+XK7tAw31DvDhS7nCXGtvQ0NlnwYAhK5bdFZuA3i46F0satRqPD+hF1+OuZbgg8kHrQNfIedPSLwo3VjYvSSc66tCRS4cL55T/DWHyUsmkeSOqGcF7edQBvkcKHpYOcQMgBm+EvZDtOFu0Q3TSXwbXuDR4iRWUCTVg8/NJTmwM2p7Ig9SGyPGZLeJHqZAkynsmCORRycjWra4aYVpJiPFx5qA2Q4n+OhyRodFCoBZwXhiDUwK5ZIruqRd2j0rqpj69Cci4Mcwq4gvDGeOMW1AgYgvAp9EXCAk45pkX/lk3pia+hk1o61lHif0cSk6xAPC97JdVW7/Mg3lc+Dm+2azq2P6ImPAPu6Y+p8DhYwDoIDeF1+lCYB5lig1IohRF9m7N5ESMCINOw8jDGZCvbCdzl9NzX5YZ4RxezvaBDNLqvJCBwrBKQ=='
    username: keycloak
    password: '{cipher}AQBCUA88keJYGKA2bIOy85HlrRVyZQhK0SRvGXYyHv3hh6fFyv2fHMtFnsPrFFIzMYOtTv0i+EPgWipcixmAHVDkLjkvckaWSUUSz+kI6Qui+B/YRBuigST4M4mrjlBNvwZsiKLNMUP46vluCOEGurq+IDtv3aNuPS5JsZ8ZDRYoqrkbjDC7jq6Gbv85Hql7bZ1Hz4kDMMahvDteb+1SwRT8p/liGLp2OcinbFeryf9ueV3DxDOJh9XzX2ByY+glMKcojVGgZJFbkIwFFJoRVFDOBkuo8gkLSAoP7BwdwgubECJ0WjU7vX8V8pwnOP8n1IzdSR9JmYHmIv8c7iLBmnYmbPTPvGVX7Y8eTS+qssI7IKBntbAj5C3Sa4wa/kce748='
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 20

#    username: sa
#    url: jdbc:h2:./data/keycloak;DB_CLOSE_ON_EXIT=FALSE
#    hikari:
#      maximum-pool-size: 25
#      minimum-idle: 1

server:
  forward-headers-strategy: native
  port: 5555
  servlet:
    context-path: "/"

logging:
  level:
    '[org.jgroups]': INFO
    '[org.infinispan]': INFO
    '[org.keycloak]': INFO
    '[org.keycloak.services.managers.DefaultBruteForceProtector]': DEBUG
    '[org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner]': DEBUG
    '[org.keycloak.services.managers.UserSessionManager]': DEBUG
    '[org.keycloak.timer.basic]': DEBUG

keycloak:
  custom:
    server:
      keycloak-path: ""

    adminUser:
      username: admin
      password: admin
      create-admin-user-enabled: true
      #
      #    migration:
      #      importProvider: singleFile
      #      importLocation: keycloak-realm-config.json
      # -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
      # -Dkeycloak.migration.strategy=IGNORE_EXISTING
#  hostname:
#    provider: "default"
#    default:
#      frontendUrl: ""
#      adminUrl: ""
#      forceBackendUrlToFrontendUrl: false
#
#  admin:
#    realm: "master"
#
#  eventsStore:
#    provider: "jpa"
#
#  eventsListener:
#    "jboss-logging":
#      "success-level": "info"
#      "error-level": "warn"
#
#  realm:
#    provider: "jpa"
#
#  user:
#    provider: "jpa"
#
#  userFederatedStorage:
#    provider: "jpa"
#
#  userSessionPersister:
#    provider: "jpa"
#
#  authorizationPersister:
#    provider: "jpa"
#
#  userCache:
#    default:
#      enabled: true
#
#  timer:
#    provider: "basic"
#
#  theme:
#    staticMaxAge: "2592000"
#    cacheTemplates: true
#    cacheThemes: true
#    folder:
#      enabled: false
#      dir: ""
#
#  scheduled:
#    interval: 900
#
#  connectionsHttpClient:
#    default: {}
#
#  connectionsJpa:
#    provider: "default"
#    default:
#      dataSource: "spring/datasource"
#      initializeEmpty: true
#      migrationStrategy: "update"
#      showSql: false
#      formatSql: true
#      globalStatsInterval: -1
#
#  realmCache:
#    default:
#      enabled: true
#
#  connectionsInfinispan:
#    default:
#      jgroupsUdpMcastAddr: "234.56.78.90"
#      nodeName: "localhost"
#      siteName: ""
#      clustered: fase
#      async: false
#      sessionsOwners: 1
#      l1Lifespan: 600000
#      remoteStoreEnabled: false
#      remoteStoreHost: "localhost"
#      remoteStorePort: 11222
#      hotrodProtocolVersion: ""
#
#  scripting: {}
#
#  "jta-lookup":
#    provider: "jboss"
#    jboss:
#      enabled: true
#
#  "login-protocol":
#    "saml":
#      "knownProtocols": ["http=${server.port}", "https=${server.port}"]
#
#  "x509cert-lookup":
#    provider: "default"
#    default:
#      enabled: true
#
#      haproxy:
#        enabled: true
#        sslClientCert: "x-ssl-client-cert"
#        sslCertChainPrefix: "x-ssl-client-cert-chain"
#        certificateChainLength: 1
#
#      apache:
#        enabled: true
#        sslClientCert: "x-ssl-client-cert"
#        sslCertChainPrefix: "x-ssl-client-cert-chain"
#        certificateChainLength: 1
#
#      nginx:
#        enabled: true
#        sslClientCert: "x-ssl-client-cert"
#        sslCertChainPrefix: "x-ssl-client-cert-chain"
#        certificateChainLength: 1
