spring:
   config:
      activate:
         on-profile: production
         
server:
  port: '8080'
  servlet:
    context-path: /api
#
# development configuration
#
spring:
  devtools:
    livereload:
      enabled: true
  # JPA 설정
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update  # create
    show-sql: 'true'
  datasource:
    # # RDS - MySQL
    url: jdbc:mysql://pofect-database.c4jotwudvoiz.ap-northeast-2.rds.amazonaws.com:3306/pofect?characterEncoding=UTF-8&serverTimezone=UTC
    username: pofect
    password: 2wh1234!!
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5555/realms/pofect-realm
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
   # mongoDB - Atlas
  data:
    mongodb:
      uri: mongodb+srv://pofect:pofect1!@pofect-mongodb.0tggaus.mongodb.net/pofect?retryWrites=true&w=majority
      # uri: '{cipher}AQA4Aav/4IAn/caU/77vWFpQJ4EHrt8QmilcABHSa3B9TlO3Js6feE3qiBzIGb7Ah+pIFNj/YALDqbuY/AJEsVbVQ99C4hkMFxV4GrIcDcs2LiwwZ4bcqYx18Frhb5h7oW3Hx47LCFp+7sj21616gzrOojMrMklNdWliHN8D4TZ6O3YTJTUcCY6MkxIQchcYjj8s3iDHIXt4vsgCCuXkrKSXU4xgtKXst+AJMVVb2zTLtNjAhK0Pc0edeoIjjSMXFmrZsjJPgNr35z4+YBnD5Gdho5WUuq0z6jQzrupCoP24c+q79CAP/Q9xNbBdt8yW3Rdeo3o7nckOI1vJnTgkyynUMIZHMZsiS6MS1eYn3wNfitZ4Xmx41vOgW7bYxqpuK3CuAc2tE1hMv0dJvhdQbGOWj7Sh1QA5T2el3PYb+9neSK6m6kXqtoqOfne5WBXb5yNJo2bASpGr5eD8pHrdP0iZaCJimQzH0kHz2IN9rNyAi0K2/9hWVQZcQ92E9HPeM/0='


logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: INFO
                              
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://52.79.114.216:8761/eureka
