spring:
   config:
      activate:
         on-profile: production
         
server:
  port: '8080'
  servlet:
    context-path: /api
#
# development configuration
#
spring:
  devtools:
    livereload:
      enabled: true
  # JPA 설정
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update  # create
    show-sql: 'true'
  datasource:
    # # RDS - MySQL
    url: jdbc:mysql://pofect-database.c4jotwudvoiz.ap-northeast-2.rds.amazonaws.com:3306/pofect?characterEncoding=UTF-8&serverTimezone=UTC
    username: pofect
    password: 2wh1234!!
    # url: '{cipher}AQDMCdhvTGjeB0NYC7RAjWfCvNR1LK0qc1cwtiaiPcd35vQqRJd2nEFEursYm9azngVdv5bSULSNtTSIZ0AvSno2UprEJGCBCZHEXCND08VjZq4RwgVfCkta2wUbYkAjuAzFTBFykcXCsL66el4Jr/rEkAZtksF/BJKw/qa09afhipS33Vc3QUSHtEb+w8HpwXAWkMzyxF2YvsEZOHUr2r8+G83sRCfOlX0BWBrEIAriNFHTjTjRon9xudHvs6q2j7ntkwN/i+dl2mlEgXMYWpiUlW2qAl+wtkt0g//Ss+RIJH5ZlLn4/E1tRFrdHYW+N3T06DpU6Iu/Otr0zWUm34IiErU4lDOEFhYnrJ4FnGoisLk9Lf18Yt/hGaLiwiv4yAqj5n0FbtIbJ51TsfSS9Fpjgc53HnSNYSvCeX8EOWqrnO1XGx52t6ciLhVXOP35bHknYhum7M3/irkK2B19v7jy822my+8Qm3gLH9R24shZlzjaMf2voH4OTQFU5E1qcyqb98DvBJJd8GR/GfjjxPHIxTA/njprGv48hTRJtr47hQ=='
    # username: pofect
    # password: '{cipher}AQCSA0rRCM47HNSs74fdY2C0mznb/A8I6Bzd2F6wFdIDE33ViWmlO6XjZ5Ob/yYUxtqfXOMHgQWwUNf5jR1Mjm8vaEhqU32QbFXNzynFtWWrYg+s4a1j8NhWIGV+XK7tAw31DvDhS7nCXGtvQ0NlnwYAhK5bdFZuA3i46F0satRqPD+hF1+OuZbgg8kHrQNfIedPSLwo3VjYvSSc66tCRS4cL55T/DWHyUsmkeSOqGcF7edQBvkcKHpYOcQMgBm+EvZDtOFu0Q3TSXwbXuDR4iRWUCTVg8/NJTmwM2p7Ig9SGyPGZLeJHqZAkynsmCORRycjWra4aYVpJiPFx5qA2Q4n+OhyRodFCoBZwXhiDUwK5ZIruqRd2j0rqpj69Cci4Mcwq4gvDGeOMW1AgYgvAp9EXCAk45pkX/lk3pia+hk1o61lHif0cSk6xAPC97JdVW7/Mg3lc+Dm+2azq2P6ImPAPu6Y+p8DhYwDoIDeF1+lCYB5lig1IohRF9m7N5ESMCINOw8jDGZCvbCdzl9NzX5YZ4RxezvaBDNLqvJCBwrBKQ=='
    # hikari:
    #   minimum-idle: 10
    #   maximum-pool-size: 20
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5555/realms/pofect-realm
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
   # mongoDB - Atlas
  data:
    mongodb:
      uri: '{cipher}AQA4Aav/4IAn/caU/77vWFpQJ4EHrt8QmilcABHSa3B9TlO3Js6feE3qiBzIGb7Ah+pIFNj/YALDqbuY/AJEsVbVQ99C4hkMFxV4GrIcDcs2LiwwZ4bcqYx18Frhb5h7oW3Hx47LCFp+7sj21616gzrOojMrMklNdWliHN8D4TZ6O3YTJTUcCY6MkxIQchcYjj8s3iDHIXt4vsgCCuXkrKSXU4xgtKXst+AJMVVb2zTLtNjAhK0Pc0edeoIjjSMXFmrZsjJPgNr35z4+YBnD5Gdho5WUuq0z6jQzrupCoP24c+q79CAP/Q9xNbBdt8yW3Rdeo3o7nckOI1vJnTgkyynUMIZHMZsiS6MS1eYn3wNfitZ4Xmx41vOgW7bYxqpuK3CuAc2tE1hMv0dJvhdQbGOWj7Sh1QA5T2el3PYb+9neSK6m6kXqtoqOfne5WBXb5yNJo2bASpGr5eD8pHrdP0iZaCJimQzH0kHz2IN9rNyAi0K2/9hWVQZcQ92E9HPeM/0='


logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: INFO
                              
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://52.79.114.216:8761/eureka
